// JavaScript Document
document.writeln("<!DOCTYPE html PUBLIC \'-//W3C//DTD XHTML 1.0 Transitional//EN\' \'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\'>");
document.writeln("<html xmlns=\'http://www.w3.org/1999/xhtml\'>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\' />");
document.writeln("<title>底部文件</title>");
document.writeln("<link rel=\'shortcut icon\' href=\'images/favicon.ico\' />");
document.writeln("<link rel=\'stylesheet\' href=\'css/global.css\' />");
document.writeln("");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<div class=\'footer-top\'>");
document.writeln("	<div class=\'_top\'>");
document.writeln("		<dl class=\'fl\'>");
document.writeln("			<dt>关于果壳</dt>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>企业荣誉</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>果壳体验店</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>代理商专区</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>加入果壳</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>联系我们</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>供应/服务商需求咨询</a></dd>");
document.writeln("		</dl>");
document.writeln("		<dl class=\'fl\'>");
document.writeln("			<dt>新闻资讯</dt>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>公司新闻</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>媒体报道</a></dd>");
document.writeln("		</dl>");
document.writeln("		<dl class=\'fl\'>");
document.writeln("			<dt>购物指南</dt>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>购物流程</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>支付方式</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>配送说明及费用</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>订单管理</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>购买常见问题</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>预置应用公示</a></dd>");
document.writeln("		</dl>");
document.writeln("		<dl class=\'fl\'>");
document.writeln("			<dt>售后服务</dt>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>售后政策</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>售后服务网点</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>上门维修</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>签收须知</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>物流查询</a></dd>");
document.writeln("		</dl>");
document.writeln("		<dl class=\'fl\'>");
document.writeln("			<dt>关注我们</dt>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>新浪微博<b></b></a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>腾讯微博<b></b></a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>QQ空间<b></b></a></dd>");
document.writeln("		</dl>");
document.writeln("	    <div class=\'icon fl\'>");
document.writeln("			<div class=\'weixin\'>");
document.writeln("			</div>");
document.writeln("	        <span>扫一扫关注微信</span>");
document.writeln("	    </div>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("<div class=\'footer-bottom\'>");
document.writeln("	<div class=\'bottom\'>");
document.writeln("		<p>网站地图|集团下属公司</p>");
document.writeln("		<div class=\'m\'>");
document.writeln("			<p class=\'fl\'>增值电信业务经营许可证：粤B2-20120350&nbsp;&nbsp; 粤ICP备05087105号&nbsp;&nbsp; 粤网文[2015]2233-484号&nbsp;&nbsp; 粤文市审[2012]196号&nbsp;&nbsp;</p>");
document.writeln("			<span class=\'ic\'><img src=\'images/zhandian/cnnic.png\' /></span>");
document.writeln("		</div>");
document.writeln("		<p>Copyright@2013 深圳市金立通信设备有限公司 版权所有</p>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");